export const MOSTRAR_PRODUCTOS = "MOSTRAR_PRODUCTOS";
export const CREAR_PRODUCTOS = "CREAR_PRODUCTOS";
export const ELIMINAR_PRODUCTOS = "ELIMINAR_PRODUCTOS";
export const ACTUALIZAR_PRODUCTOS = "ACTUALIZAR_PRODUCTOS";